project:
  type: website
  output-dir: _site

website:
  title: "In Situ Sound Design"
  description: "Un sitio web simple creado con Quarto"
  site-url: "https://ezequielabregu.github.io/in-situ-sound-design"
  repo-url: "https://github.com/ezequielabregu/in-situ-sound-design"
  
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
    right:
      - icon: github
        href: "https://github.com/ezequielabregu/in-situ-sound-design"
      - icon: linkedin
        href: "https://linkedin.com/in/tuperfil"

format:
  html:
    theme: cosmo
    #css: styles.css
    toc: true
    toc-location: left
    code-fold: true
    code-tools: true
    fig-cap-location: bottom
    smooth-scroll: true
    
execute:
  freeze: auto